### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by HoldYourWaffle** [vega/ts-json-schema-generator#104]
An inventorization of features that are missing in this module (for #101).
There might be things that you (@domoritz) don't want to add, or that I missed some. If so, please tell me and I will add them to the list.

#### Missing features
- [ ] Conditional types (#100, #93, #71)
- [ ] Selecting all types with a '*'
- [ ] Programmatic usage (at least documentation on it)

#### Nice additions
- [ ] Selecting all type in a namespace using `NamespaceName.*` ([YousefED#249](https://github.com/YousefED/typescript-json-schema/issues/249))
- [ ] Configuration inference ([YousefED#290](https://github.com/YousefED/typescript-json-schema/issues/290))
- [ ] Indentation option for output file ([YousefED#226](https://github.com/YousefED/typescript-json-schema/issues/226))

**Comment by domoritz** [comment]
Sounds good. Let me also mention that Vega-Lite would benefit from having support for conditionals so I am very much looking forward to having support for it.

**Comment by hansmbakker** [comment]
It seems that methods / function declarations are not exported.

**Comment by domoritz** [comment]
Yes, we intentionally don't support functions. See for some reasons why not: https://github.com/vega/ts-json-schema-generator/issues/98

**Comment by hansmbakker** [comment]
Ok, that's clear, thank you for the quick response.

**Comment by maneetgoyal** [comment]
@domoritz Is there a way for the schema generator to ignore the interfaces/types which have function definitions in them? I have one such interface and it is `exported` too.

**Comment by maneetgoyal** [comment]
- If it helps, I can contribute to the third task (_Programatic Use_ documentation). Was able to set up the programmatic use for my project, so should be quick to explain the usage in the README.
- The README is also missing an option on `output` file path.

**Comment by roper79** [comment]
It would be nice to have the option to add schema `$id` similarly to https://github.com/YousefED/typescript-json-schema. For example, https://github.com/ajv-validator/ajv needs it.

**Comment by antmarot** [comment]
@roper79 I agree having this natively would be a good thing. For your information though, I successfully achieved it by annotating types with `@$id` and adding the `--validationKeywords "\$id"` option to the CLI.

**Comment by domoritz** [comment]
I'm happy to review a pull request.

**Comment by Halynsky** [comment]
What about Required<Type>?
https://www.typescriptlang.org/docs/handbook/utility-types.html#requiredtype
Currently this not work:
```ts

export interface Node = {
  name?: string;
  key?: string
  // Many other properties
}

// force key to be required
export type Wrapper {
  node: Omit<Node, 'key'> & Required<Pick<Node, 'key'>>;  
}
```

Workaround:
```ts
export type Wrapper {
  node: Omit<Node, 'key'> & {key: string}>;  
}
```
But this is not very nice in scale.
